# Generated by Django 4.2.4 on 2023-08-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condidate',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='condidate',
            name='point',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='condidate',
            name='test_attempted',
            field=models.IntegerField(default=0),
        ),
    ]
