# Generated by Django 4.2.4 on 2023-08-29 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTS', '0002_alter_condidate_name_alter_condidate_point_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Condidate',
            new_name='Candidate',
        ),
    ]
