# Generated by Django 4.2.4 on 2023-11-08 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTS', '0004_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
